#!/bin/sh

dotnet build

# Fail script if necessary
if [ $? -ne 0 ]; then
    exit 1
fi

dotnet test

# Fail script if necessary
if [ $? -ne 0 ]; then
    exit 1
fi

# Format changed .cs files and add them again
FILES=$(git diff --name-only --staged -- "*.cs")
if [ -n "$FILES" ]
then
    dotnet format --include $FILES
    echo "$FILES" | xargs git add
fi

# Fail script if necessary
if [ $? -ne 0 ]; then
    exit 1
fi
