#!/bin/sh

if ! dotnet build;
then
    exit 1
fi

if ! dotnet test;
then
    exit 1
fi

# Format changed .cs files and add them again
FILES=$(git diff --name-only --staged -- "*.cs")
if [ -n "$FILES" ]
then
    if ! dotnet format --include $FILES; then
      exit 1
    fi
    echo "$FILES" | xargs git add
fi
