#!/bin/sh

found_files=$(find . -type f -name "*.sln")

# Check if any *.sln files were found
if [ -z "$found_files" ]; then
  exit 0
fi

if ! dotnet build;
then
    exit 1
fi

if ! dotnet test;
then
    exit 1
fi

# Format changed .cs files and add them again
FILES=$(git diff --name-only --staged  --diff-filter=d -- "*.cs")
if [ -n "$FILES" ]
then
    if ! dotnet format --include $FILES; then
      exit 1
    fi
    echo "$FILES" | xargs git add
fi
